### ISSUE TITLE
THIS IS UNACCEPTABLE

### ISSUE THREAD

**Issue by codingJWilliams** [perryprog/ToR-Genius#4]
THE FACT THAT WHEN YOU RUN THE COMMAND `pong` IT RETURNS `ping` IS ABSOLUTELY UNACCEPTABLE. IT HAS RUINED MY EXPERIENCE WITH THE BOT 0/10 WOULD NOT RUN AGAIN. PLEASE FIX IMMEDIATELY HIGH PRIORITY OR I WILL CAUSE YOU PAIN PERRY FRASER 😠😠😠😠😠😠😠😠😠😠😠😠

**Comment by codingJWilliams** [comment]
THIS HAS NOT BEEN FIXED YET

**Comment by codingJWilliams** [comment]
@perryprog

**Comment by perryprog** [comment]
fixed in `424327a5950323b6e5cf9c22f170f6b1d8152c37` (wrong commit message because lazy)
